# -*- coding: utf-8 -*-
"""Hash Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z2bazflLTOmQPZdvZMufqklEZ0ADeU1A
"""

user_key=int(input("enter key"))
size_array=int(input("enter size of array"))
l=[]
while True:
    print("*******METHORD*********\n 1.division\n 2.midsquare\n 3.folding\n 4.break")
    mtd=int(input("enter number 1, 2 3 or 4"))
    if mtd==1:
        r=user_key%size_array
        
        print(user_key,"stored in ",r,"th index")
    elif mtd==2:#mid square
        r=user_key**2
        r_str=str(r)
        m=len(str(r))//2
        res=r_str[m-1:m+2]
        
        print(user_key,"stored in",int(res),"th index")

    elif mtd==3:
      if user_key>=100000:
        st=str(user_key)
        a1=st[0:3]
        a2=st[3:len(st)]
        if len(a2)>3:
          a3=st[3:6]
          a4=st[6:]
   
      print(user_key,"stored in",int(a1)+int(a3)+int(a4),"th index")  

    else:
      print("**********THANK YOU************")
      break