# -*- coding: utf-8 -*-
"""HASH FUNCTION USING .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CShj0qPUP8RmvtZTYxy_-HnFQWsSRzN0
"""

user=int(input("enter number"))
if user>=100000:
    st=str(user)
    a1=st[0:3]
    a2=st[3:len(st)]
    if len(a2)>3:
        a3=st[3:6]
        a4=st[6:]
   
print(user,"stored in",int(a1)+int(a3)+int(a4),"th index")